image: alpine

stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: none
  SSH_PRIVATE_KEY: $LIBWEBRUNNER_PRIVATE_KEY
  SSH_USER: $SSH_DEPLOY_USER
  SSH_SERVER: $SSH_DEPLOY_SERVER

# Include before_script to download utilities repo & run scripts
include: 'https://content.library.unt.edu/www/utilities/raw/master/scripts/gitlab-ci/.before-script-utils-repo.yml'

.deploy:
  stage: deploy
  variables:
    UTIL_SCRIPTS: source ./prepare_ssh.sh
    GIT_SUBMODULE_STRATEGY: none
    GIT_BRANCH: master
    SITE_DEST_DIR: /home/discover/$CI_ENVIRONMENT_NAME
  script:
    - ssh $SSH_USER@$SSH_SERVER "
        cd $SITE_DEST_DIR &&
        git pull origin $GIT_BRANCH &&
        export RAILS_PORT=$RAILS_PORT &&
        export RAILS_ENV=$RAILS_ENV &&
        docker-compose down &&
        docker-compose build &&
        docker-compose run --rm web rake db:migrate &&
        docker-compose run web rails assets:precompile &&
        docker-compose up -d
        "
  when: manual

deploy:alpha:
  extends: .deploy
  environment:
    name: alpha
    url: alpha.discover.library.unt.edu
  variables:
    RAILS_PORT: 3000
    RAILS_ENV: development

deploy:beta:
  extends: .deploy
  environment:
    name: beta
    url: beta.discover.library.unt.edu
  variables:
    RAILS_PORT: 3100
    RAILS_ENV: production

deploy:production:
  extends: .deploy
  environment:
    name: production
    url: discover.library.unt.edu
  variables:
    RAILS_PORT: 3200
    RAILS_ENV: production