image: alpine

stages:
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: none
  SSH_PRIVATE_KEY: $LIBWEBRUNNER_PRIVATE_KEY
  SSH_USER: $SSH_DEPLOY_USER
  SSH_SERVER: $SSH_DEPLOY_SERVER

# Include before_script to download utilities repo & run scripts
include: 'https://content.library.unt.edu/www/utilities/raw/master/scripts/gitlab-ci/.before-script-utils-repo.yml'

test:
  image: docker:19.03.4-dind
  stage: test
  variables:
    ADD_PACKAGES: py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    RAILS_PORT: 3300
    RAILS_ENV: test
    RAILS_SERVE_STATIC_FILES: "true"
  script:
    - "pip install docker-compose"
    - "docker-compose build"
    - "docker-compose run --rm web rake db:migrate"
    - "docker-compose run --rm web rails assets:precompile"
    - "docker-compose run --rm web bundle exec rspec --format documentation"
    - "docker-compose down"
  when: manual

.deploy:
  stage: deploy
  variables:
    UTIL_SCRIPTS: source ./prepare_ssh.sh
    GIT_SUBMODULE_STRATEGY: none
    GIT_BRANCH: master
    SITE_DEST_DIR: /var/www/html/$CI_ENVIRONMENT_URL
  script:
    - ssh $SSH_USER@$SSH_SERVER "
        cd $SITE_DEST_DIR &&
        git fetch --all &&
        git checkout $CI_COMMIT_SHA &&
        export RAILS_PORT=$RAILS_PORT &&
        export RAILS_ENV=$RAILS_ENV &&
        export RAILS_SERVE_STATIC_FILES=$RAILS_SERVE_STATIC_FILES &&
        docker-compose down &&
        docker-compose build &&
        docker-compose run --rm web rake db:migrate &&
        docker-compose run --rm web rails assets:precompile &&
        docker-compose up -d
        "
  when: manual

deploy:alpha:
  extends: .deploy
  environment:
    name: alpha
    url: alpha.discover.library.unt.edu
  variables:
    RAILS_PORT: 3000
    RAILS_ENV: development
    RAILS_SERVE_STATIC_FILES: "false"

deploy:beta:
  extends: .deploy
  environment:
    name: beta
    url: beta.discover.library.unt.edu
  variables:
    RAILS_PORT: 3100
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: "true"

deploy:production:
  extends: .deploy
  environment:
    name: production
    url: discover.library.unt.edu
  variables:
    RAILS_PORT: 3200
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: "true"