inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml


Layout/AlignArguments:
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - 'db/migrate/*'
