services:
  db:
    image: docker.io/postgres:12.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      args:
        APP_BUILD_TYPE: ${APP_BUILD_TYPE:-development}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/app:z
      - bundle_cache:/bundle
      - app_tmp:/app/tmp
      - app_log:/app/log
      - node_modules:/app/node_modules
    ports:
      - "${RAILS_PORT:-3000}:3000"
      - "3036:3036"
    depends_on:
      db:
        condition: service_healthy
    restart: no
    env_file:
      - .env
    networks:
      - network

volumes:
  bundle_cache:
  app_tmp:
  app_log:
  node_modules:

networks:
  network:
