version: "3.8"
services:
  db:
    image: docker.io/postgres:12.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - network
  web:
    image: "${APP_IMAGE_NAME}"
    ports:
      - "${RAILS_PORT:-3000}:3000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    networks:
        - network

networks:
    network:
