name: discover

services:
  db:
    image: docker.io/postgres:12.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    image: "${APP_IMAGE_NAME}"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/bundle
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
volumes:
  bundle_cache:
