version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "echo $RAILS_ENV && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db
    restart: always
    environment:
      - SOLR_URL
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}